/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/encounters-search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Recherche le détails des rencontres de championnat spécifiées */
    post: operations['searchEncounters']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/encounters-poster': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Génère une affiche des rencontres au format demandé */
    post: operations['generateEncountersPoster']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/encounters-poster/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Renvoie le HTML exact qui sera transformé en image, pour itérer sur le design */
    get: operations['previewEncountersPoster']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * @description Catégorie du championnat. Par défaut, senior
     * @enum {string}
     */
    DivisionCategory: 'senior' | 'youth' | 'veteran'
    /**
     * @description Format de sortie de l'image
     * @enum {string}
     */
    ImageFormat:
      | 'instagram-square'
      | 'instagram-portrait'
      | 'instagram-story'
      | 'facebook-square'
      | 'facebook-link'
    EncountersPosterRequest: {
      /** @description Journée de championnat */
      dayNumber?: number
      /** @description Saison au format 2025/2026. Par défaut, la saison en cours */
      season?: string
      /**
       * @description Phase du championnat
       * @enum {number}
       */
      phase?: 1 | 2
      category?: components['schemas']['DivisionCategory']
      format?: components['schemas']['ImageFormat']
      /** @description Remplace le titre calculé automatiquement */
      title?: string
      /** @description Remplace le sous-titre calculé automatiquement */
      subtitle?: string
    }
    EncounterSearchRequest: {
      /** @description Journée de championnat */
      dayNumber?: number
      /** @description Saison au format 2025/2026. Par défaut, la saison en cours */
      season?: string
      /**
       * @description Phase du championnat
       * @enum {number}
       */
      phase?: 1 | 2
      category?: components['schemas']['DivisionCategory']
    }
    Encounter: {
      /**
       * Format: uuid
       * @description Identifiant de la rencontre
       */
      id?: string
      /** @description Division de la rencontre */
      division?: string
      /** @description Poule de la rencontre */
      pool?: string
      /** @description Saison au format 2025/2026 */
      season?: string
      /** @description Phase du championnat */
      phase?: number
      /** @description Journée de championnat */
      championshipDayNumber?: number | null
      /**
       * Format: date
       * @description Date de la rencontre
       */
      played_at?: string
      status?: components['schemas']['EncounterStatus']
      /** @description Score de l'équipe à domicile */
      homeScore?: number | null
      /** @description Score de l'équipe à l'extérieur */
      awayScore?: number | null
      /** @description Equipe à domicile */
      homeTeam?: components['schemas']['Team']
      /** @description Equipe à l'extérieur */
      awayTeam?: components['schemas']['Team']
    }
    Team: {
      /**
       * Format: uuid
       * @description Identifiant de l'équipe
       */
      id?: string
      /** @description Nom de l'équipe, par exemple Mellinet TT 3 */
      name?: string
      /** @description Nom du club */
      clubName?: string
      lineup?: components['schemas']['Player'][]
    }
    Player: {
      /**
       * Format: uuid
       * @description Identifiant du joueur
       */
      id?: string
      /** @description Nom du joueur */
      fullName?: string
      /** @description Nombre de points du joueur */
      points?: number
    }
    /** @enum {string} */
    EncounterStatus: 'SCHEDULED' | 'PLAYED' | 'REPORTED'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  searchEncounters: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EncounterSearchRequest']
      }
    }
    responses: {
      /** @description Résultats trouvés */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Encounter'][]
        }
      }
    }
  }
  generateEncountersPoster: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EncountersPosterRequest']
      }
    }
    responses: {
      /** @description Image générée */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/png': string
        }
      }
    }
  }
  previewEncountersPoster: {
    parameters: {
      query?: {
        dayNumber?: number
        season?: string
        phase?: 1 | 2
        category?: components['schemas']['DivisionCategory']
        format?: components['schemas']['ImageFormat']
        title?: string
        subtitle?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Document HTML de l'affiche */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/html': string
        }
      }
    }
  }
}
